# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rw_MetropolisC <- function(x0, sigma, N) {
    .Call('_StatComp20054_rw_MetropolisC', PACKAGE = 'StatComp20054', x0, sigma, N)
}

